mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:com/ktdsuniversity/edu/**/mapper/*Mapper.xml
  
spring:
  servlet:
    multipart:
      max-file-size: 100MB #1024(1kb) * 1024(1mb) * 100(100mb)
      max-request-size: 10MB
  datasource:
    url: jdbc:oracle:thin:@3.37.36.255:1521:XE
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: TEAM_A
    password: TEAM_A
  application:
    name: hello-spring
  # hello-spring application의 별도 설정(Customize)
  app:
    multipart:
  #업로드 가능한 파일들의 목록
  #업로드 가능한 목록이 더 작기에 가능한 애들 적고 업로드시마다 검사한다.
      whitelist: 
        .txt,
        .yml,
        .html,
        .css,
        text/html,
        image/png,
        image/gif,
        image/jpeg,
        image/tiff,
        application/pdf,
        application/x-tika-ooxml,
        application/x-tika-msoffice,
        application/zip,
        text/plain
#사용자가 업로드한 파일이 저장될 위치 
# C:/uploadFiles
#    base-dir: /Users/choseong-jin/Documents/uploadFiles
    base-dir:
      windows: C:/uploadFiles
      macos: /Documents/uploadFiles
    obfuscation:
#파일명을 난독화 할 것인지에 대한 여부
      enable: true
#난독화를 할 때 확장자를 가릴것인지 아닌지에 대한 설정
      hide-ext: 
        enable: true